### ISSUE TITLE
Console log output

### ISSUE THREAD

**Issue by valtido** [DeveloperToolsWG/console-object#39]
Hi, 

I would like to request for a couple features, on request we should have a method that can output everything console has recorded so far.

This is useful when you need to save it programmatically.

I would also like an event listener, so we can assign a handler and do something when there is a new entry on log, warn, error etc.

**Comment by bkardell** [comment]
Hi @valtido, this work has been taken up by WHATWG, see https://github.com/whatwg/console - you might want to take up an issue there.  You'll likely have to be a little more specific, some pseudo-code samples/use cases will help your cause.

**Comment by valtido** [comment]
thanx
